SimpleClubManager/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from main_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),  # redirect to django admin page
    url(r'^accounts/', include('django.contrib.auth.urls')),  # self manage profiles page
    url(r'^i18n/', include('django.conf.urls.i18n')),  # does the langauge check (1st browser, then user input)
]

"""
Routing for all app specific pages and function like to delete a member.
e.g.: members/(?P<member_id>[0-9]+)/$
all url's are named to have access to them within the code in other locations like views.py
"""
urlpatterns += i18n_patterns(
    url(r'^$', views.index, name='loggedInLandingPage'),
    url(r'^members/add/$', views.add_member, name='add_member'),
    url(r'^members/$', views.list_members, name='list_members'),
    url(r'^members/(?P<member_id>[0-9]+)/$', views.list_member, name='list_member'),
    url(r'^members/(?P<member_id>[0-9]+)/delete/$', views.delete_member, name='delete_member'),
    url(r'^members/(?P<member_id>[0-9]+)/edit/$', views.edit_member, name='edit_member'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^invoices/$', views.list_invoices, name='list_invoices'),
    url(r'^invoices/(?P<invoice_id>[0-9]+)/edit/$', views.edit_invoice, name='edit_invoice'),
    url(r'^invoices/create/$', views.create_invoice, name='create_invoice'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^ice_slots/$', views.list_ices, name='list_ices'),
    url(r'^ice_slots/(?P<ice_slot_id>[0-9]+)/$', views.view_ice, name='view_ice'),
    url(r'^ice_slots/add/$', views.add_ice, name='add_ice'),
    url(r'^ice_slots/(?P<ice_slot_id>[0-9]+)/edit/$', views.edit_ice, name='edit_ice'),
    url(r'^ice_slots/(?P<ice_slot_id>[0-9]+)/delete/$', views.delete_ice, name='delete_ice'),
    url(r'^impressum/', views.impressum, name='impressum'),
    url(r'^accounts/create/', views.create_account, name='create_account'),
    url(r'^trainings/$', views.list_trainings, name='list_trainings'),
    url(r'^trainings/(?P<training_id>[0-9]+)/$', views.view_training, name='view_training'),
    url(r'^trainings/(?P<training_id>[0-9]+)/unregister/$', views.unregister_from_training, name='unregister_from_training'),
    url(r'^trainings/add/$', views.add_training, name='add_training'),
    url(r'^trainings/(?P<training_id>[0-9]+)/edit/$', views.edit_training, name='edit_training'),
    url(r'^trainings/(?P<training_id>[0-9]+)/delete/$', views.delete_training, name='delete_training'),
)

main_app/models.py
"""
models.py: responsible for defining all model classes.
Django also uses this class to create a database model.
"""

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy


class City(models.Model):
    """
    Class City: with specified type checks like zip must be 4 digits
    """
    zip_regex = RegexValidator(regex=r'^\d{4}$', message=gettext_lazy("Enter correct Zip Code"))
    zip_code = models.PositiveSmallIntegerField(validators=[zip_regex])
    name = models.CharField(max_length=30)


class Club(models.Model):
    """
    Class Club: defines club name and description.
    """
    name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        """
        Overwriting to string method (otherwise it returns just the whole object of Club)
        :return: club name
        """
        return self.name


class Member(models.Model):
    """
    Class Member: linked to django default user Class to extend user attributes.
    """
    address = models.CharField(max_length=50, null=True)
    city = models.ForeignKey(City, related_name='members', null=True)
    phone_regex = RegexValidator(regex=r'^\+41\d{9}$', message=gettext_lazy("Enter a valid phone number"))
    phone_number = models.CharField(validators=[phone_regex], max_length=12, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='member')
    website = models.URLField(max_length=100, blank=True, null=True)
    club = models.ForeignKey(Club, on_delete=models.SET_NULL, null=True, related_name="members")

    def __str__(self):
        """
        Overwriting to string method (otherwise it returns just the whole object of Member)
        :return: formatted member name string in format: first name + last name
        """
        return f'{self.user.first_name} {self.user.last_name}'


@receiver(post_save, sender=User)
def create_member(sender, instance, created, **kwargs):
    """
    Hooking the create_member and save_member methods to the User model
    """
    if created:
        Member.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_member(sender, instance, **kwargs):
    """
    Hooking the create_member and save_member methods to the User model
    """
    instance.member.save()


class Invoice(models.Model):
    """
    Class Invoice: Defines a invoice
    """
    title = models.CharField(max_length=50)
    description = models.TextField(null=True)
    amount = models.IntegerField()
    due_date = models.DateField()
    create_date = models.DateField()
    paid_date = models.DateField(null=True)
    canceled = models.BooleanField(default=False)
    member = models.ForeignKey(Member, on_delete=models.PROTECT, related_name="invoices")

    def __str__(self):
        """
        Overwriting to string method (otherwise it returns just the whole object of Invoice)
        :return: string title of invoice string
        """
        return self.title


class IceSlot(models.Model):
    """
    Class IceSlot: hold start and end time of an ice slot and it links to which club it belongs
    """
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    club = models.ForeignKey(Club, on_delete=models.CASCADE, null=True, related_name="ice_slots")

    class Meta:
        ordering = ['start_time']

    def __str__(self):
        """
        Overwriting to string method (otherwise it returns just the whole object of IceSlot)
        :return: string in format: ice slot start time and ice slot end time
        """
        return f'{self.start_time.strftime("%Y-%m-%d")} {self.start_time.strftime("%H:%M")} - {self.end_time.strftime("%H:%M")}'


class Training(models.Model):
    """
    Class Training: Holds all needed training information, like who is the trainer and players
    and links it to an ice slot.
    """
    title = models.CharField(max_length=50)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    members = models.ManyToManyField(Member, related_name="trainings")
    trainer = models.ForeignKey(Member, on_delete=models.SET_NULL, null=True, related_name="trainings_as_trainer")
    club = models.ForeignKey(Club, on_delete=models.CASCADE, null=True, related_name="trainings")
    ice_slot = models.ForeignKey(IceSlot, on_delete=models.SET_NULL, null=True, related_name="trainings")

    class Meta:
        ordering = ['start_time']

    def __str__(self):
        """
        Overwriting to string method (otherwise it returns just the whole object of Training)
        :return: title of training string
        """
        return f'{self.title}: {self.start_time.strftime("%Y-%m-%Y")} {self.start_time.strftime("%H:%M")} - {self.end_time.strftime("%H:%M")}'


class SubscriptionType(models.Model):
    """
    Class SubscriptionType: gives a choice of different invoice subscription types.
    like: member fee, training camp, material sell, etc.
    """
    name = models.CharField(max_length=50)


class Subscription(models.Model):
    """
    Class Subscription: binds the invoice with subscriptions and their type.
    """
    type = models.ForeignKey(SubscriptionType, on_delete=models.SET_NULL, null=True, related_name="subscriptions")
    price = models.IntegerField()
    duration = models.IntegerField()
    description = models.TextField()
    invoice = models.ForeignKey(Invoice, on_delete=models.SET_NULL, null=True, related_name="subscriptions")

main_app/views/ice_slots.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import gettext
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse
from django.core import serializers

from main_app.forms import AddIceForm
from main_app.models import IceSlot


@require_http_methods(["GET"])
@login_required()
def list_ices(request):
    """
    List all booked ics slots
    :param request: client request
    :return: a page with a table of all ices
    """
    ice_slots = IceSlot.objects.all()
    return render(request, 'ice_slots/list_ices.html', {
        'ice_slots': ice_slots
    })


@require_http_methods(["GET", "POST"])
@login_required()
def add_ice(request):
    """
    Provides a form so user can schedule ice times
    :param request: client request
    :return: a page with add ice form
    """
    if request.method == 'POST':
        form = AddIceForm(request.POST)
        if form.is_valid():
            ice_slot = IceSlot(
                start_time=form.cleaned_data['start_time'],
                end_time=form.cleaned_data['end_time'],
                club=request.user.member.club
            )
            ice_slot.save()
            ice_slot.refresh_from_db()
            messages.add_message(request, messages.SUCCESS,
                                 gettext('Added ice-slot at {start} for club {club}').format(start=ice_slot.start_time,
                                                                                             club=ice_slot.club.name))
            return redirect('list_ices')
    else:
        form = AddIceForm()
    return render(request, 'ice_slots/add_ice.html', {
        'form': form
    })


@require_http_methods(["GET", "POST"])
@login_required()
def edit_ice(request, ice_slot_id):
    """
    View to edit a booked ice slot. e.g. it's time.
    :param request: client request
    :param ice_slot_id: id of to be modified ice slot
    :return: a page with a edit ice form
    """
    ice_slot = get_object_or_404(IceSlot, pk=ice_slot_id)
    if request.method == 'POST':
        form = AddIceForm(request.POST, instance=ice_slot)
        if form.is_valid():
            old_start = ice_slot.start_time
            old_end = ice_slot.end_time
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                 gettext(
                                     'Changed time from {old_start}-{old_end} to {start}-{end} for slot {id}').format(
                                     old_start=old_start.time(), old_end=old_end.time(), start=ice_slot.start_time.time(),
                                     end=ice_slot.end_time.time(), id=ice_slot_id))
            return redirect('list_ices')
    else:
        form = AddIceForm(instance=ice_slot)
    return render(request, 'ice_slots/add_ice.html', {
        'form': form,
    })


@require_http_methods(["POST"])
@login_required()
def delete_ice(request, ice_slot_id):
    """
    URL to delete a provided ice slot id and redirect to list ices view.
    :param request: client request
    :param ice_slot_id: id of to be deleted ice slot
    :return: success message and redirect to ice slot list or throws a error message
    """
    if request.method == 'POST':
        ice_slot = get_object_or_404(IceSlot, pk=ice_slot_id)
        ice_slot.delete()
        messages.add_message(request, messages.SUCCESS, gettext('Deleted ice_slot {id}').format(id=ice_slot_id))
        return redirect('list_ices')


@require_http_methods(["GET"])
@login_required()
def view_ice(request, ice_slot_id):
    ice_slot = get_object_or_404(IceSlot, pk=ice_slot_id)
    trainings = ice_slot.trainings.all()
    data = serializers.serialize('json', trainings, fields=('title', 'start_time', 'end_time'))
    return HttpResponse(data, content_type="application/json")

main_app/views/info.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


def index(request):
    """
    start page
    :param request:  client request
    :return: home screen
    """
    return render(request, 'index.html')


def contact(request):
    """
    Shows App. contacts
    :param request: client request
    :return: page with contact details
    """
    return render(request, 'contact.html')


def impressum(request):
    """
    Shows the impressum page
    :param request: client request
    :return: impressum page
    """
    return render(request, 'impressum.html')


@login_required()
def create_account(request):
    """
    todo: needed for multi tenancy if planned for implementation
    :param request: client request
    :return:
    """
    return render(request, 'create_account.html')

main_app/views/invoices.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.utils.translation import gettext
from django.views.decorators.http import require_http_methods

from main_app.forms import CreateInvoiceForm
from main_app.models import Invoice


@require_http_methods(["GET", "POST"])
@login_required()
def create_invoice(request):
    """
    Page for creating invoices.
    :param request: client request
    :return: page with form for creating a invoice
    """
    if request.method == 'POST':
        form = CreateInvoiceForm(request.POST)
        if form.is_valid():
            invoice = Invoice(form.instance)
            invoice.save()
            invoice.refresh_from_db()
            messages.add_message(request, messages.SUCCESS,
                                 gettext('Created {invoice_title} for club {club}').format(invoice_title=invoice.title,
                                                                                           club=invoice.club.name))
            return redirect('list_invoices')
    else:
        form = CreateInvoiceForm(club=request.user.member.club)
    return render(request, 'invoices/create_invoice.html', {
        'form': form
    })


@require_http_methods(["GET"])
@login_required()
def list_invoices(request):
    """
    Loads all active invoices and displays it to the user
    :param request: client request
    :return: returns a page with all created invoices
    """
    invoices = Invoice.objects.all()
    return render(request, 'invoices/list_invoices.html', {
        'invoices': invoices
    })


@require_http_methods(["GET", "POST"])
@login_required()
def edit_invoice(request, invoice_id):
    """
    Provides a mask for editing a invoice
    :param request: client request
    :param invoice_id: integer id of an invoice to edit
    :return: page with invoice edit mask
    """
    return render(request, 'invoices/edit_invoice.html')

main_app/templates/trainings/add_training.html
{#On this side it's possible to add a training. You have to enter all informations and to submit them.#}
{% extends "main/base.html" %}
{% load i18n %}
{#This is the changing part of the title in the jumbotron#}
{% block title %}
    {% trans "Add Training" %}
{% endblock title %}

{% block content %}
    {% load widget_tweaks %}
    <div class="col-sm-7">
        <form method="post" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <label for="Text">{% trans "Add Training" %}</label>
            </div>
            <div class="form-group">
                <label for="title">{% trans "Training" %}</label>
                {% render_field form.title class="form-control" %}
                {{ form.title.errors }}
            </div>
            <div class="form-group">
                <label for="description">{% trans "Description" %}</label>
                {% render_field form.description class="form-control" %}
                {{ form.description.errors }}
            </div>
            <div class="form-group">
                <label for="start_time">{% trans "Start Time" %}</label>
                {% render_field form.start_time class="form-control" %}
                {{ form.start_time.errors }}
            </div>
            <div class="form-group">
                <label for="end_time">{% trans "End Time" %}</label>
                {% render_field form.end_time class="form-control" %}
                {{ form.end_time.errors }}
            </div>
            <div class="form-group">
                <label for="ice_slot">{% trans "Select Ice Slot" %}</label>
                {% render_field form.ice_slot class="form-control" %}
                {{ form.ice_slot.errors }}
            </div>
            <div class="form-group">
                <ul id="trainings">
                </ul>
            </div>
            <div class="form-group">
                <label for="trainer">{% trans "Trainer" %}</label>
                {% render_field form.trainer class="form-control" %}
                {{ form.trainer.errors }}
            </div>
            <div class="form-group">
                <label for="members">{% trans "Select Members" %}</label>
                {% render_field form.members class="form-control" %}
                {{ form.members.errors }}
            </div>
            <input type="Submit" class="btn btn-default col-sm-6" value="{% trans "Submit" %}">
            <input type="Reset" class="btn btn-default col-sm-6" value="{% trans "Reset" %}">
            <script type="text/javascript">
                $('input[name="start_time"]').daterangepicker(
                    {
                        locale: {
                            format: 'YYYY-MM-DD HH:mm'
                        },
                        "singleDatePicker": true,
                        "timePicker": true,
                        "timePicker24Hour": true,
                        "timePickerIncrement": 15,
                        "autoApply": true,
                        "opens": "right",
                        "drops": "down",
                    }
                );
                $('input[name="end_time"]').daterangepicker(
                    {
                        locale: {
                            format: 'YYYY-MM-DD HH:mm'
                        },
                        "singleDatePicker": true,
                        "timePicker": true,
                        "timePicker24Hour": true,
                        "timePickerIncrement": 15,
                        "autoApply": true,
                        "opens": "right",
                        "drops": "down",
                    }
                );
                $('#id_ice_slot').change(function () {
                    var id=$(this).find(':selected')[0].value;
                    $.ajax({
                        type: 'GET',
                        url: '/ice_slots/' + id,
                        success: function (data) {
                            var trainings = $('#trainings');
                            trainings.empty();
                            for (var i = 0; i < data.length; i++) {
                                 trainings.append('<li>' + data[i].fields['title'] + ' ' + data[i].fields.start_time + '-' + data[i].fields.end_time + '</li>');
                            }
                        }
                    })
                });
            </script>
        </form>
    </div>

{% endblock content %}

main_app/templates/trainings/delete_training.html
{#This is the security request side for the deletion of a training.#}
{% extends "main/base.html" %}
{% load i18n %}
{#This is the changing part of the title in the jumbotron#}
{% block title %}
    {% trans "Delete Training" %}
{% endblock title %}

{% block content %}
    <div class="col-sm-9">
        <b>{% trans "Delete Training" %}</b>
{#        Woll Sie das Training wirklich löschen?#}
        <br><br>
        Trainingsdaten (automatisch laden)
        <br><br>
        <a class="btn btn-default btn-sm" href="/trainings" role="button">{% trans "Delete" %}</a>
        <button class="btn btn-default btn-sm" onclick="goBack()" role="button">{% trans "Reset" %}</button>

        <script>
            function goBack() {
                window.history.back();
            }
        </script>
    </div>

{% endblock content %}

main_app/templates/trainings/list_trainings.html
{#This is the entrance of this sub area. Here you can see all entrances and if necessery you can edit it immediately. You can also create an new one by clicking on the button bellow.#}
{% extends "main/base.html" %}
{% load i18n %}
{#This is the changing part of the title in the jumbotron#}
{% block title %}
    {% trans "Training overview" %}
{% endblock title %}

{% block content %}

    <div class="col-sm-9">
        <b>{% trans "Here is a list of all trainings" %}</b><br><a class="btn btn-default btn-sm"
                                                                   href="{% url 'add_training' %}"
                                                                   role="button">{% trans "Add Training" %}</a><br><br>
        {% for m in messages %}
            <div class="alert alert-{{ m.tags }} alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ m }}</strong>
            </div>
        {% endfor %}
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>{% trans "Training" %}</th>
                <th>{% trans "Trainer" %}</th>
                <th>{% trans "Date" %}</th>
                <th>{% trans "Number of participants" %}</th>
                <th class="hidden-xs">&nbsp;</th>
                <th class="hidden-xs">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            {% for t in trainings %}
                <tr>
                    <td><a href="{% url 'view_training' t.id %}">{{ t.title }}</a></td>
                    <td>{{ t.trainer.user.first_name }}</td>
                    <td>{{ t.start_time|date:"l d M Y" }} {{ t.start_time|date:"H:i" }}-{{ t.end_time|date:"H:i" }}</td>
                    <td>{{ t.members.count }}</td>
                    <td class="hidden-xs"><a class="btn btn-default btn-sm hidden-xs"
                                             href="{% url 'edit_training' t.id %}" role="button">{% trans "Edit" %}</a>
                    </td>
                    <td class="hidden-xs">
                        <form action="{% url 'delete_training' t.id %}" method="post" novalidate>
                            {% csrf_token %}
                            <input type="hidden" value="{{ t.id }}">
                            <button class="btn btn-default btn-sm hidden-xs" type="Submit">{% trans "Delete" %}</button>
                        </form>
                    </td>
                </tr>
                <tr class="hidden-sm hidden-md hidden-lg">
                    <td class="hidden-sm hidden-md hidden-lg"><a
                            class="btn btn-default btn-sm hidden-sm hidden-md hidden-lg"
                            href="{% url 'edit_training' t.id %}" role="button">{% trans "Edit" %}</a></td>
                    <td class="hidden-sm hidden-md hidden-lg">
                        <form action="{% url 'delete_training' t.id %}" method="post" novalidate>
                            {% csrf_token %}
                            <input type="hidden" value="{{ t.id }}">
                            <button class="btn btn-default btn-sm hidden-sm hidden-md hidden-lg"
                                    type="Submit">{% trans "Delete" %}</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>


{% endblock content %}

main_app/templates/trainings/view_training.html
{% extends "main/base.html" %}
{% load i18n %}
{% block title %}
    {% trans "Training overview" %}
{% endblock title %}

{% block content %}
    <div class="col-sm-7">
        <h3>{{ training.title }}</h3>
        {% for m in messages %}
            <div class="alert alert-{{ m.tags }} alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ m }}</strong>
            </div>
        {% endfor %}
        <div class="row">
            <div class="col-sm-4">{% trans "Date" %}</div>
            <div class="col-sm-4">{{ training.start_time|date:"l d M Y" }}</div>
        </div>
        <div class="row">
            <div class="col-sm-4">{% trans "Time" %}</div>
            <div class="col-sm-4">{{ training.start_time|date:"H:i" }}-{{ training.end_time|date:"H:i" }}</div>
        </div>
        <div class="row">
            <div class="col-sm-4">{% trans "Trainer" %}</div>
            <div class="col-sm-4">{{ training.trainer }}</div>
        </div>
        <div class="row">
            <div class="col-sm-4">{% trans "Participants" %}</div>
        </div>
        <div class="row">
            <ul>
                {% for m in training.members.all %}
                    <li>{{ m }} {% if m == user.member %}
                        <form action="{% url 'unregister_from_training' training.id %}" method="post" novalidate>
                            {% csrf_token %}
                            <button class="btn btn-default btn-sm" type="submit"
                                    role="button">{% trans "unregister" %}</button>
                        </form>
                    {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>
        <h4>{% trans "Description" %}</h4>
        <div class="row">
            <div class="col-sm-12">{{ training.description }}</div>
        </div>
    </div>
{% endblock content %}